### ISSUE TITLE
Icons for different types of transportation

### ISSUE THREAD

**Issue by janelucia** [kiel-live/kiel-live#132]
We want symbols for transportation like: boats and scooters.

**Comment by anbraten** [comment]
Maybe something like:

![bus](https://user-images.githubusercontent.com/6918444/170777452-9e3080c7-2adc-415f-a374-a774b61dfce5.png)

![bike](https://user-images.githubusercontent.com/6918444/170777587-b8d9b033-4457-4179-9f4d-b8115ac68400.png)

![Screenshot from 2022-05-27 21-26-09](https://user-images.githubusercontent.com/6918444/170777464-d3b7edec-acd6-4382-abd0-a045aaf24fd7.png)

**Comment by anbraten** [comment]
One app I saw show markers with an icon for a specific zoom level and uses colored points for higher zoom levels which looks quite nice as well.

**Comment by anbraten** [comment]
![image](https://user-images.githubusercontent.com/6918444/220844913-0dc5e7d4-3402-4995-9981-ab1a8f0555ee.png)

@janelucia @lukashass What do you think?

**Comment by janelucia** [comment]
@anbraten I like the idea, but the outlined icon looks a bit like the DB logo

![image](https://user-images.githubusercontent.com/95575343/220899178-6e88146f-3814-45b7-b594-e886ba273231.png)

**Comment by anbraten** [comment]
- bus vehicle markers should use the old icon for now (number with location nose)
- vehicle markers without pin nose
- 
- How should selected markers look like?

**Comment by anbraten** [comment]
![image](https://user-images.githubusercontent.com/6918444/220920203-18c0360f-fc05-4ff2-ba15-395dcc9c53a9.png)
